name: Maven Build & Sonar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-sonar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build (compile & test)
      run: mvn -B clean verify

    - name: SonarQube Analysis
      env:
        SONAR_HOST_URL: http://34.229.165.151:9000
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        echo "SONAR_HOST_URL=${SONAR_HOST_URL}"
        if [ -z "${SONAR_HOST_URL}" ]; then
          echo "ERROR: SONAR_HOST_URL is empty." >&2
          exit 1
        fi
        if [ -z "${SONAR_TOKEN}" ]; then
          echo "ERROR: SONAR_TOKEN secret is missing." >&2
          exit 1
        fi

        echo "Checking connectivity to SonarQube..."
        curl -sS -I "${SONAR_HOST_URL}" || { echo "ERROR: Cannot reach ${SONAR_HOST_URL}"; exit 1; }

        mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
          -Dsonar.projectKey=JavaWebApp \
          -Dsonar.host.url="${SONAR_HOST_URL}" \
          -Dsonar.login="${SONAR_TOKEN}"
