name: Maven CI-CD (Build • SonarQube • Nexus • Tomcat)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}   # allow manual runs

jobs:
  build-test-sonar-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build & Test
      run: mvn -B clean verify

    # ---- SONARQUBE ANALYSIS ----
    - name: SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # REQUIRED: add in repo Settings → Secrets
      run: |
        if [ -z "${SONAR_TOKEN}" ]; then
          echo "ERROR: SONAR_TOKEN secret is missing." >&2
          exit 1
        fi

        echo "Using Sonar host from pom.xml: $(mvn -q help:evaluate -Dexpression=sonar.host.url -DforceStdout)"
        mvn -B sonar:sonar -Dsonar.login="${SONAR_TOKEN}"

    # ---- NEXUS DEPLOY ----
    - name: Configure Maven settings.xml for Nexus
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}   # REQUIRED
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}   # REQUIRED
      run: |
        if [ -z "${NEXUS_USERNAME}" ] || [ -z "${NEXUS_PASSWORD}" ]; then
          echo "WARNING: Nexus credentials not provided; skipping deploy step." >&2
          exit 0
        fi

        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << 'EOF'
        <settings>
          <servers>
            <server>
              <id>maven-releases</id>
              <username>${env.NEXUS_USERNAME}</username>
              <password>${env.NEXUS_PASSWORD}</password>
            </server>
            <!-- Add snapshot server here if you add snapshotRepository in pom.xml -->
          </servers>
        </settings>
        EOF

    - name: Deploy to Nexus (if credentials present)
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        if [ -z "${NEXUS_USERNAME}" ] || [ -z "${NEXUS_PASSWORD}" ]; then
          echo "Skipping Nexus deploy because credentials are not set."
          exit 0
        fi
        mvn -B deploy

    # ---- TOMCAT DEPLOY ----
    - name: Deploy WAR to Tomcat (Manager API)
      if: always()  # run even if previous step skipped; will self-check env
      env:
        TOMCAT_HOST: 18.207.93.131                   # Tomcat IP/host
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}      # REQUIRED for Tomcat deploy
        TOMCAT_PASS: ${{ secrets.TOMCAT_PASS }}      # REQUIRED for Tomcat deploy
        TOMCAT_CONTEXT_PATH: /JavaWebApp             # change to your desired context path
      run: |
        # Require credentials
        if [ -z "${TOMCAT_USER}" ] || [ -z "${TOMCAT_PASS}" ]; then
          echo "Skipping Tomcat deploy because TOMCAT_USER/PASS not set."
          exit 0
        fi

        WAR_FILE=$(ls target/*.war 2>/dev/null | head -n 1)
        if [ -z "$WAR_FILE" ]; then
          echo "No WAR produced in target/. Ensure <packaging>war</packaging> in pom.xml." >&2
          exit 1
        fi

        echo "Attempting deploy of ${WAR_FILE} to http://${TOMCAT_HOST}:8080${TOMCAT_CONTEXT_PATH}"

        # Optionally undeploy first (ignore errors if not existing)
        curl -sS -u "${TOMCAT_USER}:${TOMCAT_PASS}" \
          "http://${TOMCAT_HOST}:8080/manager/text/undeploy?path=${TOMCAT_CONTEXT_PATH}" || true

        # Deploy/Update
        curl -sS -u "${TOMCAT_USER}:${TOMCAT_PASS}" \
          --upload-file "$WAR_FILE" \
          "http://${TOMCAT_HOST}:8080/manager/text/deploy?path=${TOMCAT_CONTEXT_PATH}&update=true"

    # ---- (Optional) Upload the built WAR as a GitHub artifact ----
    - name: Upload WAR artifact
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: webapp-war
        path: target/*.war
        if-no-files-found: warn
