# .github/workflows/maven-build.yml
name: Maven Build & Sonar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-sonar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build (compile & test)
      run: mvn -B clean verify

    - name: SonarQube Analysis
      env:
        SONAR_HOST_URL: http://34.229.165.151:9000   # <-- ensure this is correct & reachable
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      # <-- create this secret in GitHub
      run: |
        echo "Using Sonar host: ${SONAR_HOST_URL}"
        # Optional: quick connectivity check
        curl -sS -I ${SONAR_HOST_URL} || true

        mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
          -Dsonar.projectKey=JavaWebApp \
          -Dsonar.host.url=${SONAR_HOST_URL} \
          -Dsonar.login=${SONAR_TOKEN}
